### ISSUE TITLE
Missing error descriptions.

### ISSUE THREAD

**Issue by InEx-Niklas** [kivra/developer.kivra.com#39]
Hello, Kivra.
During testing today we got the following undocumented error codes.
The following errors came when we tried to add an icon 

[/v2/tenant/{tenantKey}/icon](https://github.com/kivra/developer.kivra.com/blob/9987b102803c4079a07fc0d91e8b3f0bebc20e88/swagger.yml#L887)

Tried to upload a 1px large image.
**40030: IconSizeError** 

Tried to upload a gif.
**40028: UnsupportedFileType**

They are not present in the error [codes section.](https://github.com/kivra/developer.kivra.com/blob/9987b102803c4079a07fc0d91e8b3f0bebc20e88/swagger.yml#L526)

With regards Niklas, InExchange.

**Comment by paolokivra** [comment]
Thanks Niklas,
great feedback!! I will make sure we update the list.
//Paolo

**Comment by paolokivra** [comment]
The documentation is now updated
